# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - SmartStorage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_URL_2: ${{ secrets.DATABASE_URL_2 }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DEBUG: "prisma:*" # <--- Log detalhado do Prisma

    steps:
      - name: 📦 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🧩 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'



      - name: 'Install Prisma CLI'
        working-directory: ./Code/backend
        run: npm install --save-dev prisma

      - name: 'Generate Prisma Client'
        working-directory: ./Code/backend
        run: npx prisma generate

      - name: 'Apply database migrations'
        working-directory: ./Code/backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: build e test backend
        working-directory: ./Code/backend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          zip -r backend.zip .

      - name: 📦 Upload artifact para o deploy
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./Code/backend/backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_URL_2: ${{ secrets.DATABASE_URL_2 }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: 📥 Baixar artifact do job de build
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./Code/backend
      
      - name: 🔐 Login na Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7048918B5F3E47F4B965664567439AF4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A804F04995404C48938A6CB7CBFF3810 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_438721A167D94AE891BBF334902B35ED }}

      - name: 🚀 Deploy para o Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SmartStorage'
          slot-name: 'Production'
          package: ./Code/backend/backend.zip
          